services:
  dev:
    image: node:20-alpine
    user: "root"
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - COREPACK_DEFAULT_TO_LATEST=0
    ports:
      - 4321:4321
      - 4322:4322
    command: sh -c "corepack enable && sh && pnpm install --frozen-lockfile && pnpm dev --host 0.0.0.0"
volumes:
  pnpm-store: