name: Build and Deploy
on:
  push:
    branches: [master]
  repository_dispatch:
    types: [wordpress_update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build
        uses: actions/checkout@v4
        run: |
          npm ci
          npm run build
        env:
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
      - name: Deploy to Server
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy YOUR_BUILD_DIRECTORY --project-name=YOUR_PROJECT_NAME